# Permalinks
permalink:        {{ baseurl }}

# Setup
title:            '@ziishaned'
tagline:          PHP and Javascript fanatic, open source lover and tinkerer.
url:              http://zeeshanu.github.io
paginate:         1
baseurl:          /
author:
  name:           Zeeshan Ahmed
  url:            http://zeeshanu.github.io
  email:          ziishaned@gmail.com
  github:         http://github.com/zeeshanu
  description:    'I am Zeeshan Ahmed, a full stack web developer.'

# Custom vars
version:          0.0.1
github:
  repo:           https://github.com/zeeshanu/zeeshanu.github.io

# Menu
pages_list:       
  Archive: '/archive'
  About: '/about'
  Feed: '/atom.xml'

# Stay in touch
external_links:
  'github.com/zeeshanu': 'http://github.com/zeeshanu'
  'ziishaned@gmail.com': 'mailto:ziishaned@gmail.com'
  'pk.linkedin.com/in/zeshanu': 'http://pk.linkedin.com/in/zeshanu'

plugins:          [jekyll-paginate, rouge]
paginate:         10
paginate_path: "/blog/page:num"
highlighter: rouge